// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg2ToODXR-LIzE4pl_TRiah3K8N1OYRXo',
    appId: '1:1069706226664:web:9e4effbb73e7b92a90d25d',
    messagingSenderId: '1069706226664',
    projectId: 'ecoutourisme',
    authDomain: 'ecoutourisme.firebaseapp.com',
    storageBucket: 'ecoutourisme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV6kGNnyWyKsZhMeKFYTul0qNkZJcb_7k',
    appId: '1:1069706226664:android:2b547865cbdefad390d25d',
    messagingSenderId: '1069706226664',
    projectId: 'ecoutourisme',
    storageBucket: 'ecoutourisme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFzVPw9Sz006BnfqNJRFBhUrJZXdJZEY',
    appId: '1:1069706226664:ios:fea066a5bf13e3f590d25d',
    messagingSenderId: '1069706226664',
    projectId: 'ecoutourisme',
    storageBucket: 'ecoutourisme.firebasestorage.app',
    iosClientId: '1069706226664-0nf7laqi9jqbd6mha1ktrf7m3h2u1gn4.apps.googleusercontent.com',
    iosBundleId: 'com.ecoguide.ecoguide',
  );
}
