import 'package:ecoguide/models/site_model.dart';
import 'package:ecoguide/models/itinerary_model.dart';
import 'package:ecoguide/models/booking_model.dart';

class MockDataService {
  static List<Site> getMockSites() {
    return [
      Site(
        id: '1',
        name: 'Réserve Naturelle de Camargue',
        description:
            'La Camargue est une région naturelle française située au bord de la mer Méditerranée. Elle est connue pour ses paysages uniques, ses flamants roses et ses chevaux sauvages. C\'est l\'une des plus grandes zones humides d\'Europe occidentale.',
        latitude: 43.4567,
        longitude: 4.6278,
        photos: [
          'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800',
          'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800',
          'https://images.unsplash.com/photo-1551799517-eb8f03cb5e6a?w=800',
        ],
        animals: ['Flamants roses', 'Chevaux de Camargue', 'Taureaux', 'Hérons', 'Aigrettes'],
        plants: ['Tamaris', 'Salicorne', 'Roseaux', 'Iris des marais'],
        ecoTips: [
          'Restez sur les sentiers balisés pour protéger la végétation',
          'Ne nourrissez pas les animaux sauvages',
          'Emportez vos déchets et utilisez les poubelles de tri',
          'Privilégiez les jumelles pour observer les oiseaux sans les déranger',
        ],
        type: 'reserve',
        rating: 4.8,
      ),
      Site(
        id: '2',
        name: 'Parc National des Calanques',
        description:
            'Les Calanques sont un massif littoral s\'étendant entre Marseille et Cassis. Ce parc national offre des paysages spectaculaires de falaises calcaires plongeant dans la mer turquoise. Un paradis pour les randonneurs et les amoureux de la nature.',
        latitude: 43.2165,
        longitude: 5.4500,
        photos: [
          'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
          'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
          'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        ],
        animals: ['Goélands', 'Lézards ocellés', 'Balbuzards pêcheurs', 'Puffins'],
        plants: ['Pin d\'Alep', 'Romarin', 'Thym', 'Lavande sauvage'],
        ecoTips: [
          'Respectez la réglementation du parc national',
          'Évitez les visites en période de forte chaleur (risque incendie)',
          'Privilégiez le transport en commun pour accéder au parc',
          'Ne cueillez rien et ne laissez aucune trace',
        ],
        type: 'park',
        rating: 4.9,
      ),
      Site(
        id: '3',
        name: 'Forêt de Fontainebleau',
        description:
            'La forêt de Fontainebleau est l\'une des plus grandes et des plus belles forêts de France. Elle abrite une biodiversité exceptionnelle et des rochers célèbres pour l\'escalade. Un poumon vert aux portes de Paris.',
        latitude: 48.4166,
        longitude: 2.6333,
        photos: [
          'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
          'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800',
          'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
        ],
        animals: ['Cerfs', 'Sangliers', 'Écureuils', 'Pics verts', 'Renards'],
        plants: ['Chênes sessiles', 'Hêtres', 'Bouleaux', 'Bruyères', 'Fougères'],
        ecoTips: [
          'Ne cueillez pas les fleurs ni les champignons sans autorisation',
          'Gardez votre chien en laisse pendant la période de reproduction',
          'Respectez le silence de la forêt pour la faune',
          'Utilisez les sentiers de grande randonnée (GR)',
        ],
        type: 'forest',
        rating: 4.6,
      ),
      Site(
        id: '4',
        name: 'Dune du Pilat',
        description:
            'La dune du Pilat est la plus haute dune d\'Europe avec ses 110 mètres. Elle offre une vue imprenable sur le bassin d\'Arcachon et la forêt des Landes. Un site naturel exceptionnel en constante évolution.',
        latitude: 44.5925,
        longitude: -1.2108,
        photos: [
          'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
          'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
          'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800',
        ],
        animals: ['Oiseaux migrateurs', 'Lézards des dunes', 'Huîtriers pie'],
        plants: ['Oyats', 'Pins maritimes', 'Immortelles des dunes'],
        ecoTips: [
          'Utilisez les escaliers pour monter et préserver la dune',
          'Ne descendez pas par les zones protégées et végétalisées',
          'Respectez la végétation dunaire fragile',
          'Évitez les heures de pointe en été',
        ],
        type: 'beach',
        rating: 4.7,
      ),
      Site(
        id: '5',
        name: 'Gorges du Verdon',
        description:
            'Les Gorges du Verdon sont le plus grand canyon d\'Europe avec des falaises atteignant 700 mètres. Les eaux turquoise du Verdon serpentent au fond de ce paysage spectaculaire. Un site incontournable pour les amateurs de nature.',
        latitude: 43.7647,
        longitude: 6.4023,
        photos: [
          'https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800',
          'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
          'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
        ],
        animals: ['Vautours fauves', 'Chamois', 'Truites', 'Aigles royaux'],
        plants: ['Chênes verts', 'Lavandes', 'Buis', 'Genévriers'],
        ecoTips: [
          'Réservez vos activités nautiques à l\'avance en été',
          'Respectez les zones de quiétude pour les rapaces',
          'Privilégiez les visites hors saison pour moins d\'impact',
          'Utilisez des produits solaires éco-responsables',
        ],
        type: 'canyon',
        rating: 4.9,
      ),
      Site(
        id: '6',
        name: 'Baie de Somme',
        description:
            'La Baie de Somme est l\'une des plus belles baies du monde. Elle accueille la plus grande colonie de phoques de France et des millions d\'oiseaux migrateurs. Un écosystème unique entre terre et mer.',
        latitude: 50.2167,
        longitude: 1.6333,
        photos: [
          'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
          'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800',
        ],
        animals: ['Phoques gris', 'Phoques veaux-marins', 'Spatules', 'Avocettes', 'Tadornes'],
        plants: ['Salicornes', 'Obiones', 'Asters maritimes', 'Spartines'],
        ecoTips: [
          'Traversez la baie uniquement avec un guide agréé',
          'Respectez une distance de 50m minimum avec les phoques',
          'Observez les oiseaux depuis les observatoires',
          'Ne marchez pas dans les prés salés fragiles',
        ],
        type: 'wetland',
        rating: 4.7,
      ),
    ];
  }

  static List<Itinerary> getMockItineraries() {
    return [
      Itinerary(
        id: '1',
        name: 'Boucle des Flamants Roses',
        description:
            'Une randonnée magique à travers les marais pour observer les flamants roses dans leur habitat naturel. Idéal pour les photographes et les ornithologues amateurs.',
        waypoints: [
          LatLngPoint(latitude: 43.4567, longitude: 4.6278),
          LatLngPoint(latitude: 43.4590, longitude: 4.6300),
          LatLngPoint(latitude: 43.4610, longitude: 4.6250),
          LatLngPoint(latitude: 43.4567, longitude: 4.6278),
        ],
        distanceKm: 8.5,
        durationMinutes: 120,
        transportMode: 'walking',
        difficulty: 'easy',
        siteIds: ['1'],
        imageUrl: 'https://images.unsplash.com/photo-1551799517-eb8f03cb5e6a?w=800',
        photos: [
          'https://images.unsplash.com/photo-1551799517-eb8f03cb5e6a?w=800',
          'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800',
          'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800',
          'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800',
        ],
        equipment: ['Jumelles', 'Chapeau', 'Crème solaire', 'Eau (2L minimum)', 'Appareil photo'],
        pointsOfInterest: ['Observatoire des flamants', 'Marais salants', 'Point de vue panoramique', 'Zone de nidification'],
        bestSeason: 'Printemps et automne',
        estimatedCarbonKg: 0,
        elevationGain: 20,
        region: 'Provence-Alpes-Côte d\'Azur',
      ),
      Itinerary(
        id: '2',
        name: 'Circuit des Calanques',
        description:
            'Une randonnée sportive offrant des vues spectaculaires sur les calanques et la mer Méditerranée. Parcours mythique entre Marseille et Cassis.',
        waypoints: [
          LatLngPoint(latitude: 43.2165, longitude: 5.4500),
          LatLngPoint(latitude: 43.2200, longitude: 5.4600),
          LatLngPoint(latitude: 43.2150, longitude: 5.4700),
        ],
        distanceKm: 12.0,
        durationMinutes: 300,
        transportMode: 'walking',
        difficulty: 'hard',
        siteIds: ['2'],
        imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
        photos: [
          'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
          'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
          'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
          'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
        ],
        equipment: ['Chaussures de randonnée', 'Eau (3L minimum)', 'Chapeau', 'Crème solaire', 'Maillot de bain', 'Pique-nique'],
        pointsOfInterest: ['Calanque de Sugiton', 'Calanque de Morgiou', 'Belvédère des deux Frères', 'Col de la Saoupe'],
        bestSeason: 'Printemps et automne (fermé en été)',
        estimatedCarbonKg: 0,
        elevationGain: 650,
        region: 'Provence-Alpes-Côte d\'Azur',
      ),
      Itinerary(
        id: '3',
        name: 'Vélo en Forêt de Fontainebleau',
        description:
            'Un parcours à vélo à travers la forêt de Fontainebleau, passant par les sites les plus emblématiques et les chaos rocheux célèbres.',
        waypoints: [
          LatLngPoint(latitude: 48.4166, longitude: 2.6333),
          LatLngPoint(latitude: 48.4200, longitude: 2.6500),
          LatLngPoint(latitude: 48.4100, longitude: 2.6600),
        ],
        distanceKm: 25.0,
        durationMinutes: 150,
        transportMode: 'cycling',
        difficulty: 'moderate',
        siteIds: ['3'],
        imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
        photos: [
          'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
          'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800',
          'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
          'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
        ],
        equipment: ['Vélo VTT', 'Casque', 'Gourde', 'Kit de réparation', 'Barres énergétiques'],
        pointsOfInterest: ['Rochers d\'Apremont', 'Mare aux Fées', 'Gorges de Franchard', 'Désert d\'Apremont'],
        bestSeason: 'Toute l\'année',
        estimatedCarbonKg: 0,
        elevationGain: 180,
        region: 'Île-de-France',
      ),
      Itinerary(
        id: '4',
        name: 'Sentier du Verdon',
        description:
            'Une randonnée époustouflante le long des Gorges du Verdon avec des panoramas à couper le souffle sur le plus grand canyon d\'Europe.',
        waypoints: [
          LatLngPoint(latitude: 43.7647, longitude: 6.4023),
          LatLngPoint(latitude: 43.7700, longitude: 6.4100),
          LatLngPoint(latitude: 43.7750, longitude: 6.4200),
        ],
        distanceKm: 14.0,
        durationMinutes: 300,
        transportMode: 'walking',
        difficulty: 'hard',
        siteIds: ['5'],
        imageUrl: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800',
        photos: [
          'https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800',
          'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
          'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
          'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800',
        ],
        equipment: ['Chaussures de randonnée', 'Bâtons', 'Eau (3L)', 'Lampe frontale', 'Casse-croûte', 'Vêtement de pluie'],
        pointsOfInterest: ['Point Sublime', 'Belvédère de la Carelle', 'Sentier Blanc-Martel', 'Balcons de la Mescla'],
        bestSeason: 'Mai à Octobre',
        estimatedCarbonKg: 0,
        elevationGain: 720,
        region: 'Provence-Alpes-Côte d\'Azur',
      ),
      Itinerary(
        id: '5',
        name: 'Découverte de la Dune du Pilat',
        description:
            'Une balade familiale autour de la plus haute dune d\'Europe avec vue sur le bassin d\'Arcachon et la forêt de pins.',
        waypoints: [
          LatLngPoint(latitude: 44.5925, longitude: -1.2108),
          LatLngPoint(latitude: 44.5950, longitude: -1.2150),
          LatLngPoint(latitude: 44.5900, longitude: -1.2080),
        ],
        distanceKm: 5.0,
        durationMinutes: 90,
        transportMode: 'walking',
        difficulty: 'easy',
        siteIds: ['4'],
        imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
        photos: [
          'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
          'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
          'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800',
          'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800',
        ],
        equipment: ['Chaussures fermées', 'Chapeau', 'Lunettes de soleil', 'Eau', 'Appareil photo'],
        pointsOfInterest: ['Sommet de la dune', 'Vue sur le Banc d\'Arguin', 'Plage de la Corniche', 'Forêt usagère'],
        bestSeason: 'Printemps et automne',
        estimatedCarbonKg: 0,
        elevationGain: 110,
        region: 'Nouvelle-Aquitaine',
      ),
      Itinerary(
        id: '6',
        name: 'Safari Phoques en Baie de Somme',
        description:
            'Une excursion unique pour observer les phoques dans leur milieu naturel, accompagné d\'un guide naturaliste.',
        waypoints: [
          LatLngPoint(latitude: 50.2167, longitude: 1.6333),
          LatLngPoint(latitude: 50.2200, longitude: 1.6400),
          LatLngPoint(latitude: 50.2250, longitude: 1.6500),
        ],
        distanceKm: 10.0,
        durationMinutes: 180,
        transportMode: 'walking',
        difficulty: 'moderate',
        siteIds: ['6'],
        imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
        photos: [
          'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
          'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800',
          'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
        ],
        equipment: ['Bottes ou chaussures étanches', 'Jumelles', 'Vêtements chauds', 'Coupe-vent', 'Appareil photo longue focale'],
        pointsOfInterest: ['Pointe du Hourdel', 'Colonie de phoques', 'Parc du Marquenterre', 'Observatoires ornithologiques'],
        bestSeason: 'Été (juillet-août)',
        estimatedCarbonKg: 0,
        elevationGain: 10,
        region: 'Hauts-de-France',
      ),
      Itinerary(
        id: '7',
        name: 'Tour du Lac d\'Annecy à Vélo',
        description:
            'Une boucle cyclable familiale autour du plus beau lac des Alpes françaises, entre montagnes et eaux turquoise.',
        waypoints: [
          LatLngPoint(latitude: 45.8992, longitude: 6.1294),
          LatLngPoint(latitude: 45.8500, longitude: 6.1500),
          LatLngPoint(latitude: 45.8200, longitude: 6.1700),
        ],
        distanceKm: 42.0,
        durationMinutes: 180,
        transportMode: 'cycling',
        difficulty: 'easy',
        siteIds: [],
        imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800',
        photos: [
          'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800',
          'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
          'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
          'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
        ],
        equipment: ['Vélo de route ou VTC', 'Casque', 'Lunettes', 'Maillot de bain', 'Serviette', 'Pique-nique'],
        pointsOfInterest: ['Vieille ville d\'Annecy', 'Château de Duingt', 'Réserve du Bout du Lac', 'Plage d\'Albigny'],
        bestSeason: 'Mai à Septembre',
        estimatedCarbonKg: 0,
        elevationGain: 150,
        region: 'Auvergne-Rhône-Alpes',
      ),
      Itinerary(
        id: '8',
        name: 'Randonnée au Cirque de Gavarnie',
        description:
            'Une randonnée mythique vers l\'un des plus beaux cirques des Pyrénées, classé au patrimoine mondial de l\'UNESCO.',
        waypoints: [
          LatLngPoint(latitude: 42.7333, longitude: -0.0167),
          LatLngPoint(latitude: 42.7200, longitude: -0.0100),
          LatLngPoint(latitude: 42.7100, longitude: -0.0050),
        ],
        distanceKm: 11.0,
        durationMinutes: 240,
        transportMode: 'walking',
        difficulty: 'moderate',
        siteIds: [],
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
        photos: [
          'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
          'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
          'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800',
          'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
        ],
        equipment: ['Chaussures de montagne', 'Bâtons', 'Eau', 'Vêtements chauds', 'Coupe-vent', 'Crème solaire'],
        pointsOfInterest: ['Grande Cascade (423m)', 'Cirque glaciaire', 'Pont de neige', 'Vue sur la Brèche de Roland'],
        bestSeason: 'Juin à Septembre',
        estimatedCarbonKg: 0,
        elevationGain: 450,
        region: 'Occitanie',
      ),
    ];
  }

  static List<Activity> getMockActivities() {
    return [
      Activity(
        id: '1',
        name: 'Éco-lodge des Marais',
        description:
            'Hébergement écologique au cœur de la Camargue avec vue sur les étangs. Construction en matériaux naturels et énergie 100% renouvelable.',
        type: 'accommodation',
        pricePerPerson: 85.0,
        imageUrl: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
        siteId: '1',
        isEcoFriendly: true,
        ecoLabels: ['Label Clef Verte', 'Écolabel Européen'],
      ),
      Activity(
        id: '2',
        name: 'Safari Photo Camargue',
        description:
            'Excursion guidée pour photographier la faune sauvage de Camargue. Petits groupes pour minimiser l\'impact sur l\'environnement.',
        type: 'activity',
        pricePerPerson: 45.0,
        imageUrl: 'https://images.unsplash.com/photo-1551799517-eb8f03cb5e6a?w=800',
        siteId: '1',
        isEcoFriendly: true,
        ecoLabels: ['ATR - Agir pour un Tourisme Responsable'],
      ),
      Activity(
        id: '3',
        name: 'Kayak des Calanques',
        description:
            'Exploration des calanques en kayak avec guide naturaliste. Découverte de la faune marine et des grottes inaccessibles à pied.',
        type: 'activity',
        pricePerPerson: 55.0,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
        siteId: '2',
        isEcoFriendly: true,
        ecoLabels: ['Qualité Tourisme'],
      ),
      Activity(
        id: '4',
        name: 'Gîte de la Forêt',
        description:
            'Maison d\'hôtes en pleine forêt, construction bois certifié PEFC et énergie solaire. Petit-déjeuner bio et local inclus.',
        type: 'accommodation',
        pricePerPerson: 65.0,
        imageUrl: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800',
        siteId: '3',
        isEcoFriendly: true,
        ecoLabels: ['Gîtes de France', 'Écolabel Européen'],
      ),
      Activity(
        id: '5',
        name: 'Observation des Vautours',
        description:
            'Sortie accompagnée pour observer les vautours fauves dans les Gorges du Verdon. Jumelles fournies, guide ornithologue.',
        type: 'activity',
        pricePerPerson: 35.0,
        imageUrl: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800',
        siteId: '5',
        isEcoFriendly: true,
        ecoLabels: ['LPO - Ligue pour la Protection des Oiseaux'],
      ),
      Activity(
        id: '6',
        name: 'Traversée de la Baie de Somme',
        description:
            'Traversée guidée de la baie à pied, découverte des écosystèmes, observation des phoques. Pieds nus dans les sables mouvants.',
        type: 'activity',
        pricePerPerson: 25.0,
        imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
        siteId: '6',
        isEcoFriendly: true,
        ecoLabels: ['Guide Nature Certifié'],
      ),
    ];
  }
}
